version: '3.8'
services:
   #  my-app:
  #     image: 668178087276.dkr.ecr.eu-west-2.amazonaws.com/my-app:v1
 #      ports: 
#         - 3000:3000
 #       environment:
 #        - MONGO_DB_USERNAME=admin
 #        - MONGO_DB_PWD=password
      mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
         - 27017:27017
        environment: 
         - MONGO_INITDB_ROOT_USERNAME=admin
         - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
         - docker-data:/data/db
      mongo-express:
        image: mongo-express:latest
        restart: unless-stopped
        ports:
         - 8081:8081
        environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
         - ME_CONFIG_MONGODB_ADMINPASSWORD=password
         - ME_CONFIG_MONGODB_SERVER=mongodb  
volumes:
   docker-data:
      driver: local 
